import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Provider";
import Navbar from "@/components/Navbar/page";
import { ToastContainer, toast } from "react-toastify";
import TogeltoDark from "@/components/Togledark/page";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"], 
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto", 
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} `}>
        <AuthProvider>
          <Navbar />
          {children}
          <TogeltoDark />
          <ToastContainer />
        </AuthProvider>
      </body>
    </html>
  );
}
